### ISSUE TITLE
some questions for localTransactionBuilder

### ISSUE THREAD

**Issue by lhjokg** [GrapeBaBa/sui4j#107]
sui链的未签名交易可以不依赖节点rpc方法，离线方式构建出来得到txBytes吗？

**Comment by GrapeBaBa** [comment]
This class will be deprecated. AFAIK, there are some read rpc methods must be invoked such as reference price, owned objects. It may do that all offline, but I follow the official SDK approach, so it can't implement in sui4j right now.

**Comment by lhjokg** [comment]
> Please use https://github.com/GrapeBaBa/sui4j/blob/main/src/main/java/io/sui/models/transactions/TransactionBlock.java

thanks
