### ISSUE TITLE
Some interfaces are gone，Some interfaces do not exist

### ISSUE THREAD

**Issue by anchorite01** [GrapeBaBa/sui4j#108]
### Some interfaces are gone
For example：
https://docs.sui.io/sui-jsonrpc#sui_getCheckpoint
https://docs.sui.io/sui-jsonrpc#sui_getCheckpoints
https://docs.sui.io/sui-jsonrpc#sui_getLatestCheckpointSequenceNumber
....

### Some interfaces do not exist：
For example：
io.sui.Sui#getCheckpointContents
io.sui.Sui#getCheckpointContentsByDigest
io.sui.Sui#getCheckpointSummary
....

### Some returned data structures have less data：
For example：
https://docs.sui.io/sui-jsonrpc#sui_getTransactionBlock
response:
{
  "jsonrpc": "2.0",
  "result": {
    "digest": "J2eyeXQgHPUc6hE2CZ49ZGmpWskaWPfWBt8Db3uy4YHH",
    "transaction": {
      "data": {
        "messageVersion": "v1",
        ...
    "balanceChanges": [
      {
        "owner": {
          "AddressOwner": "0x041129288a2e778d2347dc506247f6f01f7018b1fb52ae2e38b806b95a743967"
        },
        "coinType": "0x2::sui::SUI",
        "amount": "-1009880"
      }
    ],
    "timestampMs": "1682415972527",
    "checkpoint": "1087877"
  },
  "id": 1
}

io.sui.models.transactions.TransactionBlockResponse  There is no balanceChanges field

**Comment by GrapeBaBa** [comment]
already updated.

**Comment by anchorite01** [comment]
The 'balanceChanges' field mentioned above still does not exist
